/**
 * VAmPI
 * OpenAPI v3 specs for VAmPI
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2004 { 
    message?: string;
    status?: InlineResponse2004.StatusEnum;
}
export namespace InlineResponse2004 {
    export type StatusEnum = 'success' | 'fail';
    export const StatusEnum = {
        Success: 'success' as StatusEnum,
        Fail: 'fail' as StatusEnum
    };
}